

1. ¿De cuáles departamentos se tiene información? 
	/Course_Catalog/Department/@Code
	/Course_Catalog/Department/Title
	/Course_Catalog/Department/Title/text()

2. ¿Cuál es la información del curso Introduction to Databases? 
	/Course_Catalog/Department/Course[Title[text()="Introduction to Databases"]]
	/Course_Catalog/Department/Course[Title[text()="Introduction to Databases"]]/@*
	/Course_Catalog/Department/Course[Title[text()="Introduction to Databases"]]/*

3. ¿Cuántos cursos están detallados? ¿Cuáles son? 
	/Course_Catalog/Department/Course[Description[text()]]/Title/text()

4. ¿Cuál es el total de inscripciones de los cursos? 
	sum(/Course_Catalog/Department/Course[@Enrollment]/number(@Enrollment))
	
5. ¿De cuáles cursos no se conoce el número de inscritos?
	/Course_Catalog/Department/Course[not(@Enrollment)]/Title/text()
	
6. ¿Cuáles cursos son iniciales (no tienen prerrequisitos)? [Nombre]
	/Course_Catalog/Department/Course[not(Prerequisites)]/Title/text()
	
7. ¿Cuáles cursos son finales (no son prerrequisitos de ninguno)? [Nombre]
    /Course_Catalog/Department/Course[not ((//Prereq/text())=@Number)] / Title
	
8. ¿Cuáles cursos tienen como instructores al director de su departamento?
	/Course_Catalog/Department/Course[parent::*/Chair/Professor/Last_Name/text() = Instructors/Professor/Last_Name/text()]/Title/text()
	
9. ¿Cuáles cursos de un departamento tienen el mismo profesor? 
	/Course_Catalog/Department/Course[/Instructors/Professor/@Last_Name = /following-sibling::*/Instructors/Professor/@Last_Name]/Title
	
10. ¿Cuáles directores de departamento no colaboran en cursos?[Toda la información] 
	/Course_Catalog/Department/Chair[not(Professor/Last_Name/text() = parent::*/Course/Instructors/Professor/Last_Name/text())]/Professor/Last_Name/text()
	
/* B. Consultas quiz Standford */

1. Return all Title elements (of both departments and courses). (16)
	*//Title
	
2. Return last names of all department chairs. (3)
	*//Chair/Professor/Last_Name/text()
	
3. Return titles of courses with enrollment greater than 500. (2)
	*//Course[@Enrollment > 500]/Title

4. Return titles of departments that have some course that takes "CS106B" as a prerequisite. (2)
	/Course_Catalog/Department/Course[Prerequisites/Prereq/text()= "CS106B"]/Title

5. Return last names of all professors or lecturers who use a middle initial. Don't worry about eliminating
	duplicates. (5)
	*//Course/Instructors/(Professor|Lecturer)[Middle_Initial]/Last_Name/text()
	
6. Return the title of courses that have a cross-listed course (i.e., that have "Cross-listed" in their
	description). (2) 
	/Course_Catalog/Department/Course[contains(Description/text(),"Cross-listed")]/Title/text()

7. Return the enrollment of all courses in the CS department. (10)
	*//Department[@Code="CS"]/Course/@Enrollment

8. Return last names of instructors teaching at least one course that has "system" in its description and
	enrollment greater than 100. (2)
	*//Course[@Enrollment>100 and contains(Description,"system")]/Instructors//Last_Name

9.  Return the title of the course with more than 2 instructors (*)(1)
	*//Course[count(Instructors/*)>2]/Title
	
10. . Return course numbers of courses that have the same title as some other course. (Hint: You might want to
	use the "preceding" and "following" navigation axes for this query, which were not covered in the video or
	our demo script; they match any preceding or following node, not just siblings.) (2)
	*//Course[(following::Course/Title = Title) or (preceding::Course/Title = Title)]/@Number
	
11.  Return the courses numbers of courses that have no lecturers as instructors. (*)(10)
	*//Course[Instructors[count(Lecturer)=0]]/@Number

12. Return titles of courses taught by the chair of a department. For this question, you may assume that all professors have distinct last names. (1)
	/Course_Catalog/Department/Course[parent::*/Chair/Professor/Last_Name/text() = Instructors/Professor/Last_Name/text()]/Title/text()
	
13. Return titles of courses taught by a professor with the last name "Ng" and by a professor with the last
	name "Thrun". (*)(1)
	*//Course[Instructors/Professor[Last_Name/text()="Ng"or text()="Thrun"]]/Title/text()
	
14. Return course numbers of courses that have a course taught by Eric Roberts as a prerequisite. (4)

	*//Course[Prerequisites/Prereq/text()=/*//Course[Instructors/Professor[First_Name/text()="Eric"and Last_Name/text()="Roberts"]]/@Number]/@Number

15. Return last names of instructors teachiing at least one course that has system in its description and
	enrollment greater than 100.(2)
	
	*//Course[contains(Description,"system")and @Enrollment>100]/Instructors//Last_Name/text()
	
D.Esquema

/*<?xml version="1.0"?>

<!DOCTYPE Courses[
	<!ELEMENT Course_Catalog (Departments)>
	<!ELEMENT Departments (Department)>
	<!ELEMENT Department (Title,Chairs,Courses)>
	<!ELEMENT Title (#PCDATA) >
	<!ELEMENT Chairs (Chair)>
	<!ELEMENT Chair (Professors)>
	<!ELEMENT Professors (Professor)>
	<!ELEMENT Professor (First_Name,Middle_Initial,Last_Name)>
	<!ELEMENT First_Name (#PCDATA)>
	<!ELEMENT Middle_Initial (#PCDATA)>
	<!ELEMENT Last_Name (#PCDATA)>
	<!ELEMENT Courses (Course)>
	<!ELEMENT Course (Title,Description,Instructors,Prerequisites)>
	<!ELEMENT Description (#PCDATA) >
	<!ELEMENT Instructors (Lecturers,Professors)>
	<!ELEMENT Lecturers (Lecturer)>
	<!ELEMENT Lecturer (First_Name,Middle_Initial,Last_Name)>
	<!ELEMENT Prerequisites (Prereq)>
	<!ELEMENT Prereq (#PCDATA) >
	<!ATTLIST Department Code ID #REQUIRED>
	<!ATTLIST Course Number ID #REQUIRED
			  Enrollment CDATA #IMPLIED>
]>*/

E.Nuevos datos

<?xml version="1.0"?>

<!DOCTYPE Course_Catalog[
	<!ELEMENT Course_Catalog (Departments)>
	<!ELEMENT Departments (Department)+>
	<!ELEMENT Department (Title,Chairs,Courses)>
	<!ELEMENT Title (#PCDATA) >
	<!ELEMENT Chairs (Chair)>
	<!ELEMENT Chair (Professors)>
	<!ELEMENT Professors (Professor)>
	<!ELEMENT Professor (First_Name,Middle_Initial?,Last_Name)>
	<!ELEMENT First_Name (#PCDATA)>
	<!ELEMENT Middle_Initial (#PCDATA)>
	<!ELEMENT Last_Name (#PCDATA)>
	<!ELEMENT Courses (Course)+>
	<!ELEMENT Course (Title,Description,Instructors,Prerequisites)>
	<!ELEMENT Description (#PCDATA) >
	<!ELEMENT Instructors (Lecturer | Professor)+>
	<!ELEMENT Lecturers (Lecturer)>
	<!ELEMENT Lecturer (First_Name,Middle_Initial,Last_Name)>
	<!ELEMENT Prerequisites (Prereq)+>
	<!ELEMENT Prereq (#PCDATA) >
	<!ATTLIST Department Code ID #REQUIRED>
	<!ATTLIST Course Number ID #REQUIRED
			  Enrollment CDATA #IMPLIED>
]>


<Course_Catalog>
<Departments>
<Department Code="AYED">
<Title>Algoritmos y Estructuras de Datos</Title>
<Chairs>
<Chair>
<Professors>
<Professor>
<First_Name>Irma</First_Name>
<Last_Name>Diaz</Last_Name>
</Professor>
</Professors>
</Chair>
</Chairs>
<Courses>
<Course Number="D-203" Enrollment="23">
<Title>Algoritmos y Estructuras de Datos</Title>
<Description>
Introduction to the engineering of computer applications emphasizing in modilar programming.
</Description>
<Instructors>
<Professor>
<First_Name>Sebastian</First_Name>
<Last_Name>Martinez</Last_Name>
</Professor>
</Instructors>
<Prerequisites>
<Prereq>AYPR</Prereq>
<Prereq>MMIN</Prereq>
</Prerequisites>
</Course>
<Course Number="C4-102" Enrollment="21">
<Title>Algoritmos y Estructuras de Datos</Title>
<Description>
Introduction to the engineering of computer applications emphasizing in modilar programming.
</Description>
<Instructors>
<Professor>
<First_Name>Guillermo</First_Name>
<Last_Name>Alvarez</Last_Name>
</Professor>
</Instructors>
<Prerequisites>
<Prereq>AYPR</Prereq>
<Prereq>MMIN</Prereq>
</Prerequisites>
</Course>
</Courses>
</Department>
<Department Code="TPRO">
<Title>Teoría de la Programación</Title>
<Chairs>
<Chair>
<Professors>
<Professor>
<First_Name>Raul</First_Name>
<Middle_Initial>A.</Middle_Initial>
<Last_Name>Chaparro</Last_Name>
</Professor>
</Professors>
</Chair>
</Chairs>
<Courses>
<Course Number="C7-203">
<Title>Teoría de la Programación</Title>
<Description>logical matter</Description>
<Instructors>
<Professor>
<First_Name>Raul</First_Name>
<Last_Name>Chaparro</Last_Name>
</Professor>
</Instructors>
<Prerequisites>
<Prereq>MATD</Prereq>
</Prerequisites>
</Course>
</Courses>
</Department>
</Departments>
</Course_Catalog>



PUNTO DOS. (XML – Oracle) AfterRide. TRevisión

Este punto vamos a perfeccionar uno de los atributos de la base de datos.
1) Proponga la estructura XML necesaria para tener la información de la revisión de un
registro. DTD y ejemplos XML OK y XML NoOK. Explique.

<?xml version="1.0"?>

<!DOCTYPE Detalles_Registro[

<!ELEMENT Detalles_Registro (Registro) >
<!ELEMENT Registro (Segmento , Persona , revision , comentario , Version , Carrera ) >
<!ELEMENT Revision (#PCDATA) >
<!ELEMENT Comentario (#PCDATA) >
<!ELEMENT Segmento (Puntos) >
<!ELEMENT Version EMPTY>
<!ELEMENT Puntos (Punto_Inicial , Punto_Final) >
<!ELEMENT Carrera EMPTY >
<!ELEMENT Punto_Final EMPTY >
<!ELEMENT Punto_Inicial EMPTY>
<!ELEMENT Persona (Ciclista) >
<!ELEMENT Ciclista EMPTY >

<!ATTLIST Registro numero ID #REQUIRED
		  fecha CDATA #REQUIRED
		  tiempo CDATA #REQUIRED
		  posicion CDATA  #REQUIRED
		  dificultad ( A | M | B ) #REQUIRED >
<!ATTLIST Segmento nombre ID #REQUIRED 
		  tipo ( C | M | L ) #REQUIRED 
<!ATTLIST Punto_Inicial idPunto ID #REQUIRED 
	      nombre CDATA #REQUIRED
		  carrera IDREF #REQUIRED >
<!ATTLIST Punto_Final idPunto ID #REQUIRED 
	      nombre CDATA #REQUIRED
		  carrera IDREF #REQUIRED >
<!ATTLIST Version idVersion ID #REQUIRED
		  nombre CDATA #REQUIRED
		  fecha CDATA #REQUIRED
		  carrera IDREF #REQUIRED >
<!ATTLIST Carrera codigo ID #REQUIRED 
		  nombre CDATA #REQUIRED >
<!ATTLIST id CDATA #REQUIRED
		  Persona nombres CDATA #REQUIRED 
		  >
<!ATTLIST Ciclista nacimiento CDATA #REQUIRED 
		  categoria ( 1 | 2 | 3 | 4 | 5 ) #REQUIRED >
]>	

<Detalles_Registro>
	<Registro
		numero = "R1"
		fecha = "06/10/2005"
		tiempo = "5"
		posicion = "10"
		dificultad = "A">
		<Segmento
			nombre = "SE001"
			tipo = "M"
			<Puntos>
				<Punto_Inicial
					idPunto = "10"
					nombre = "Punto inicial"
					carrera = "C001">
				</Punto_Inicial>
				<Punto_Final
					idPunto = "10"
					nombre = "Punto inicial"
					carrera = "C001">
				</Punto_Final>
			</Puntos>
		</Segmento>
		<Persona id = "D-1014308690">
			<Ciclista
				nacimiento = "06/10/1999"
				categoria = "1" >
			</Ciclista>
		</Persona>
		<Revision> Secciones de descenso del segmento</Revision>
		<Comentario>Dificil</Comentario>
		<Version
			idVersion = "VE001"
			nombre = "2019-1"
			carrera = "C001">
		</Version>
		<Carrera
			codigo = "C001"
			nombre = "Tour de Francia">
		</Carrera>
	</Registro>
</Detalles_Registro>
	
		



